packages:
  - packages/*
  - apps/*
  - packages/server/test/mock-backend/fixtures
  - packages/server/test/local-backend/fixtures

allowBuilds:
  "@parcel/watcher": false
  "@scarf/scarf": false
  "@swc/core": false
  esbuild: false
  keytar: false
  msgpackr-extract: false
  opensrc: false
  puppeteer: false
  sharp: true

minimumReleaseAgeExclude:
  - "@effect/tsgo-darwin-arm64@0.33.0"
  - "@effect/tsgo-darwin-x64@0.33.0"
  - "@effect/tsgo-linux-arm64@0.33.0"
  - "@effect/tsgo-linux-arm@0.33.0"
  - "@effect/tsgo-linux-x64@0.33.0"
  - "@effect/tsgo-win32-arm64@0.33.0"
  - "@effect/tsgo-win32-x64@0.33.0"
  - "@effect/tsgo@0.33.0"

overrides:
  convex: 1.43.0
  effect: 3.22.1
  "@effect/platform-node-shared": 0.61.1
  "@effect/typeclass": 0.41.0
  react: 19.2.8
  react-dom: 19.2.8

packageExtensions:
  "@mintlify/mdx":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "next-mdx-remote-client":
    peerDependencies:
      react: "*"
      react-dom: "*"

peerDependencyRules:
  allowedVersions:
    react: "19"
    react-dom: "19"
