packages:
  - packages/*
  - apps/*
  - packages/server/test/mock-backend/fixtures
  - packages/server/test/local-backend/fixtures

allowBuilds:
  "@parcel/watcher": false
  "@scarf/scarf": false
  "@swc/core": false
  esbuild: false
  keytar: false
  msgpackr-extract: false
  opensrc: false
  puppeteer: false
  sharp: true

overrides:
  convex: 1.42.1
  convex-test: 0.0.54
  effect: 3.22.0
  "@effect/typeclass": 0.41.0
  react: 19.2.7
  react-dom: 19.2.7

packageExtensions:
  "@mintlify/mdx":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "next-mdx-remote-client":
    peerDependencies:
      react: "*"
      react-dom: "*"

peerDependencyRules:
  allowedVersions:
    react: "19"
    react-dom: "19"
