name: "Confect Packages Setup"
description: "Sets up Node.js and pnpm for the confect packages"
author: "Confect"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Build Confect packages
      run: pnpm --filter "@confect/*" build
      shell: bash
