/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as basicSchemaOperations from "../basicSchemaOperations.js";
import type * as clearDatabase from "../clearDatabase.js";
import type * as confectFunctions from "../confectFunctions.js";
import type * as insertNote from "../insertNote.js";
import type * as insertTodo from "../insertTodo.js";
import type * as listNotes from "../listNotes.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  basicSchemaOperations: typeof basicSchemaOperations;
  clearDatabase: typeof clearDatabase;
  confectFunctions: typeof confectFunctions;
  insertNote: typeof insertNote;
  insertTodo: typeof insertTodo;
  listNotes: typeof listNotes;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
