// Auto-generated by Confect Error Types Generator
// Do not edit this file manually
// This file should be committed to version control for other developers and CI/CD
// This file is automatically loaded when you import @rjdellecese/confect/react/effect

import type { NotFoundError } from './convex/functions'

// Module augmentation for main react module
declare module '@rjdellecese/confect/react' {
  interface ConfectErrorTypes {
    "functions.insertNote": NotFoundError
    "functions.listNotes": NotFoundError
  }
}

// Module augmentation for effect-atom module
declare module '@rjdellecese/confect/react/effect-atom' {
  interface ConfectErrorTypes {
    "functions.insertNote": NotFoundError
    "functions.listNotes": NotFoundError
  }
}
// biome-ignore lint/complexity/noUselessEmptyExport: <auto-generated>
export {}

// Helper types for individual functions
export type FunctionsInsertNoteErrors = NotFoundError
export type FunctionsListNotesErrors = NotFoundError

// Auto-load this module when @monorepo/confect/react/effect is imported
declare global {
  namespace ConfectTypes {
    interface ErrorTypesLoaded {
      [key: string]: any
    }
  }
}

// This ensures the module is loaded when any part of confect is imported
export {}
