name: CI (example)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/example-setup
      - run: pnpm run typecheck

  build-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/example-setup
      - run: pnpm run build